#include "config_defaults.h"

// FIELD_DEF(field_name_in_cfg,           ".ini param name",               INIT_MACRO,                    default_value)
FIELD_DEF(resolution, "Resolution", INIT_INT_ARRAY2, ((int[2]){DEFAULT_RESOLUTION_WIDTH, DEFAULT_RESOLUTION_HEIGHT}))
FIELD_DEF(n_iterations, "Iterations", INIT_INT, DEFAULT_ITERATIONS)
FIELD_DEF(ssaa_level, "SSAA", INIT_INT, DEFAULT_SSAA_LEVEL)
FIELD_DEF(step_size, "Stepsize", INIT_DOUBLE, DEFAULT_STEPSIZE)
FIELD_DEF(camera_pos, "Cameraposition", INIT_VEC3D, ((Vec3d)DEFAULT_CAMERA_POS))
FIELD_DEF(tan_fov, "Fieldofview", INIT_DOUBLE, DEFAULT_TAN_FOV)
FIELD_DEF(look_at, "Lookat", INIT_VEC3D, ((Vec3d)DEFAULT_LOOK_AT))
FIELD_DEF(up_vector, "Upvector", INIT_VEC3D, ((Vec3d)DEFAULT_UP_VECTOR))
FIELD_DEF(distort, "Distort", INIT_BOOL, DEFAULT_DISTORT)
FIELD_DEF(disk_inner_radius, "Diskinner", INIT_DOUBLE, DEFAULT_DISK_INNER_RADIUS)
FIELD_DEF(disk_outer_radius, "Diskouter", INIT_DOUBLE, DEFAULT_DISK_OUTER_RADIUS)
FIELD_DEF(horizon_grid, "Horizongrid", INIT_BOOL, DEFAULT_HORIZON_GRID)
FIELD_DEF(disk_texture_mode, "Disktexture", INIT_DISK_TEXTURE_MODE, DEFAULT_DISK_TEXTURE_MODE)
FIELD_DEF(sky_texture_mode, "Skytexture", INIT_SKY_TEXTURE_MODE, DEFAULT_SKY_TEXTURE_MODE)
FIELD_DEF(sky_disk_ratio, "Skydiskratio", INIT_DOUBLE, DEFAULT_SKY_DISK_RATIO)
FIELD_DEF(fog_do, "Fogdo", INIT_BOOL, DEFAULT_FOG_DO)
FIELD_DEF(fog_mult, "Fogmult", INIT_DOUBLE, DEFAULT_FOG_MULT)
FIELD_DEF(fog_skip, "Fogskip", INIT_INT, DEFAULT_FOG_SKIP)
FIELD_DEF(blur_do, "Blurdo", INIT_BOOL, DEFAULT_BLUR_DO)
FIELD_DEF(airy_bloom, "Airy_bloom", INIT_BOOL, DEFAULT_AIRY_BLOOM)
FIELD_DEF(airy_radius, "Airy_radius", INIT_DOUBLE, DEFAULT_AIRY_RADIUS)
FIELD_DEF(gain, "Gain", INIT_DOUBLE, DEFAULT_GAIN)
FIELD_DEF(normalize, "Normalize", INIT_DOUBLE, DEFAULT_NORMALIZE)
FIELD_DEF(aces_exposure, "ACESExposure", INIT_DOUBLE, DEFAULT_ACES_EXPOSURE)
FIELD_DEF(srgb_out, "sRGBOut", INIT_BOOL, DEFAULT_SRGB_OUT)
FIELD_DEF(srgb_in, "sRGBIn", INIT_BOOL, DEFAULT_SRGB_IN)
FIELD_DEF(disk_multiplier, "Diskmultiplier", INIT_DOUBLE, DEFAULT_DISK_MULTIPLIER)
FIELD_DEF(disk_intensity_do, "Diskintensitydo", INIT_BOOL, DEFAULT_DISK_INTENSITY_DO)
FIELD_DEF(redshift, "Redshift", INIT_DOUBLE, DEFAULT_REDSHIFT)
FIELD_DEF(disk_add_structure, "Diskaddstructure", INIT_BOOL, DEFAULT_DISK_ADD_STRUCTURE)
FIELD_DEF(disk_structure_spiral_arms, "Diskstructure_spiral_arms", INIT_INT, DEFAULT_DISK_STRUCTURE_SPIRAL_ARMS)
FIELD_DEF(disk_structure_rings_freq, "Diskstructure_rings_freq", INIT_VEC3D, ((Vec3d)DEFAULT_DISK_STRUCTURE_RINGS_FREQ))
FIELD_DEF(disk_structure_spiral_pitch, "Diskstructure_spiral_pitch", INIT_DOUBLE, DEFAULT_DISK_STRUCTURE_SPIRAL_PITCH)
FIELD_DEF(disk_structure_position_variation, "Diskstructure_position_variation", INIT_DOUBLE, DEFAULT_DISK_STRUCTURE_POSITION_VARIATION)
FIELD_DEF(disk_structure_modulation, "Diskstructure_modulation", INIT_DOUBLE, DEFAULT_DISK_STRUCTURE_MODULATION)
